# Generated by Django 5.0.2 on 2025-03-01 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joo', '0003_venuebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joo.restaurantpartner')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
