# Generated by Django 5.0.2 on 2025-03-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joo', '0004_restaurantbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantbooking',
            name='restaurant_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
