# Generated by Django 5.0.2 on 2025-03-01 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joo', '0005_restaurantbooking_restaurant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuebooking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='venuebooking',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='venuebooking',
            name='venue_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
