# Generated by Django 5.0.2 on 2025-03-01 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joo', '0006_venuebooking_created_at_venuebooking_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('partner_type', models.CharField(choices=[('restaurant', 'Restaurant Partner'), ('venue', 'Venue Partner'), ('delivery', 'Delivery Partner')], max_length=20)),
                ('otp', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
